-- SCRIPT: SISTEMA DE CURRÍCULOS (RESUMES)
-- Execute no Editor SQL do Supabase

-- 1. Criar Tabela de Currículos
CREATE TABLE IF NOT EXISTS resumes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT REFERENCES jobs(id) ON DELETE CASCADE,
    candidate_name TEXT NOT NULL,
    candidate_email TEXT,
    candidate_phone TEXT,
    file_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    notes TEXT
);

-- 2. Habilitar RLS na tabela
ALTER TABLE resumes ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Segurança (RLS) para a Tabela
-- Apenas administradores podem fazer tudo
DROP POLICY IF EXISTS "Admin acesso total resumes" ON resumes;
CREATE POLICY "Admin acesso total resumes"
ON resumes FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

-- 4. Configurar Storage para os arquivos (PDF/DOCX/IMG)
-- Inserir o bucket se não existir
INSERT INTO storage.buckets (id, name, public)
VALUES ('resumes', 'resumes', true)
ON CONFLICT (id) DO NOTHING;

-- 5. Políticas de Segurança (RLS) para o Storage
-- Remover políticas antigas para evitar conflito
DROP POLICY IF EXISTS "Admin Upload Resumes" ON storage.objects;
DROP POLICY IF EXISTS "Admin Select Resumes" ON storage.objects;
DROP POLICY IF EXISTS "Admin Delete Resumes" ON storage.objects;
DROP POLICY IF EXISTS "Public Access Resumes" ON storage.objects;

-- Admin pode fazer upload
CREATE POLICY "Admin Upload Resumes"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'resumes' AND auth.role() = 'authenticated' );

-- Admin pode atualizar/deletar
CREATE POLICY "Admin Update Delete Resumes"
ON storage.objects FOR UPDATE
USING ( bucket_id = 'resumes' AND auth.role() = 'authenticated' );

CREATE POLICY "Admin Delete Resumes"
ON storage.objects FOR DELETE
USING ( bucket_id = 'resumes' AND auth.role() = 'authenticated' );

-- Acesso público para leitura (necessário para baixar o arquivo, mesmo que a URL seja gerada)
-- Ou podemos restringir apenas para auth se preferir, mas 'public' facilita o download direto via link
CREATE POLICY "Public Access Resumes"
ON storage.objects FOR SELECT
USING ( bucket_id = 'resumes' );
