-- CORREÇÃO DE PERMISSÕES PARA SISTEMA DE CURRÍCULOS
-- Execute TODO este script no Editor SQL do Supabase

-- =====================================================
-- 1. TABELA RESUMES
-- =====================================================

-- Garantir que a tabela existe
CREATE TABLE IF NOT EXISTS resumes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT REFERENCES jobs(id) ON DELETE CASCADE,
    candidate_name TEXT NOT NULL,
    candidate_email TEXT,
    candidate_phone TEXT,
    file_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    notes TEXT
);

-- Habilitar RLS
ALTER TABLE resumes ENABLE ROW LEVEL SECURITY;

-- Remover políticas antigas
DROP POLICY IF EXISTS "Admin acesso total resumes" ON resumes;
DROP POLICY IF EXISTS "Acesso total resumes" ON resumes;
DROP POLICY IF EXISTS "Public read resumes" ON resumes;
DROP POLICY IF EXISTS "Public insert resumes" ON resumes;

-- Política para permitir todas as operações (tabela interna do admin)
-- Como é uma tabela gerenciada apenas pelo dashboard admin, permitimos acesso total
CREATE POLICY "Acesso total resumes"
ON resumes FOR ALL
USING (true)
WITH CHECK (true);

-- =====================================================
-- 2. STORAGE BUCKET RESUMES
-- =====================================================

-- Criar bucket se não existir
INSERT INTO storage.buckets (id, name, public)
VALUES ('resumes', 'resumes', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Remover TODAS as políticas antigas do storage para o bucket resumes
DROP POLICY IF EXISTS "Admin Upload Resumes" ON storage.objects;
DROP POLICY IF EXISTS "Admin Update Delete Resumes" ON storage.objects;
DROP POLICY IF EXISTS "Admin Delete Resumes" ON storage.objects;
DROP POLICY IF EXISTS "Public Access Resumes" ON storage.objects;
DROP POLICY IF EXISTS "Resumes Upload Policy" ON storage.objects;
DROP POLICY IF EXISTS "Resumes Select Policy" ON storage.objects;
DROP POLICY IF EXISTS "Resumes Delete Policy" ON storage.objects;
DROP POLICY IF EXISTS "Resumes Update Policy" ON storage.objects;

-- Política para permitir upload no bucket resumes (público, pois é gerenciado pelo admin)
CREATE POLICY "Resumes Upload Policy"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'resumes');

-- Política para permitir leitura no bucket resumes
CREATE POLICY "Resumes Select Policy"
ON storage.objects FOR SELECT
USING (bucket_id = 'resumes');

-- Política para permitir atualização no bucket resumes
CREATE POLICY "Resumes Update Policy"
ON storage.objects FOR UPDATE
USING (bucket_id = 'resumes');

-- Política para permitir deleção no bucket resumes
CREATE POLICY "Resumes Delete Policy"
ON storage.objects FOR DELETE
USING (bucket_id = 'resumes');

